### PR TITLE
TICTACTOE - IOERRORHANDLING

### PR DESCRIPTION
**Pull request by 21mooie**
I noticed the input error handling resulted in a while loop so I adjusted that. If you have any feedback on this please let me know. I am interested in getting my first successful pull request.

### CODE REVIEW

**Comment by tapaswenipathak** [comment]
@21mooie Did you test the changes?

**Comment by 21mooie** [comment]
Yeah I did.

**Comment by tapaswenipathak** [comment]
Cool! Thanks and congratulations for your first pull request! 🎆

**Comment by 21mooie** [comment]
Thanks a bunch. I really appreciate it!

**Pull request merged**
